import type { Question } from "./types";

export const QUESTION_BANK: Record<string, Question[]> = {
  "6": [
    { q: "What is the chemical symbol for water?", o: ["HO", "H₂O", "WA", "OHH"], a: 1, f: "Water is H₂O — two hydrogen atoms bonded to one oxygen atom." },
    { q: "Which organ pumps blood throughout the body?", o: ["Liver", "Lung", "Brain", "Heart"], a: 3, f: "The heart is a muscular organ that pumps blood through the circulatory system." },
    { q: "What is the process by which plants make food?", o: ["Respiration", "Photosynthesis", "Digestion", "Transpiration"], a: 1, f: "Photosynthesis uses sunlight, water, and CO₂ to produce glucose and oxygen." },
    { q: "Which planet is closest to the Sun?", o: ["Venus", "Earth", "Mercury", "Mars"], a: 2, f: "Mercury is the closest planet to the Sun, though Venus is sometimes the hottest." },
    { q: "What is the unit of force?", o: ["Joule", "Watt", "Newton", "Pascal"], a: 2, f: "Force is measured in Newtons (N), named after Sir Isaac Newton." },
    { q: "Which gas do plants absorb during photosynthesis?", o: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], a: 2, f: "Plants absorb CO₂ and release O₂ during photosynthesis — the opposite of animals." },
    { q: "What is the hardest natural substance on Earth?", o: ["Iron", "Diamond", "Quartz", "Gold"], a: 1, f: "Diamond scores 10 on the Mohs scale — the highest possible hardness." },
    { q: "Which part of the cell controls its activities?", o: ["Cytoplasm", "Cell wall", "Nucleus", "Vacuole"], a: 2, f: "The nucleus contains DNA and acts as the control center of the cell." },
    { q: "What type of energy does food contain?", o: ["Kinetic", "Chemical", "Thermal", "Sound"], a: 1, f: "Food stores chemical energy, which our bodies convert into other forms of energy." },
    { q: "What is the boiling point of water at sea level?", o: ["90°C", "95°C", "100°C", "110°C"], a: 2, f: "Water boils at 100°C (212°F) at standard atmospheric pressure (sea level)." },
  ],
  "7": [
    { q: "What is the formula for speed?", o: ["Speed = Distance × Time", "Speed = Distance / Time", "Speed = Time / Distance", "Speed = Force × Mass"], a: 1, f: "Speed = Distance ÷ Time. For example, 100m in 10s = 10 m/s." },
    { q: "Which type of rock is formed from cooled lava?", o: ["Sedimentary", "Metamorphic", "Igneous", "Limestone"], a: 2, f: "Igneous rock forms when magma or lava cools and solidifies." },
    { q: "What is the powerhouse of the cell?", o: ["Nucleus", "Ribosome", "Mitochondria", "Chloroplast"], a: 2, f: "Mitochondria produce ATP, the cell's energy currency, through cellular respiration." },
    { q: "Which electromagnetic wave has the shortest wavelength?", o: ["Radio waves", "Microwaves", "Visible light", "Gamma rays"], a: 3, f: "Gamma rays have the shortest wavelength and highest energy in the EM spectrum." },
    { q: "What is the chemical formula for carbon dioxide?", o: ["CO", "C₂O", "CO₂", "C₂O₂"], a: 2, f: "CO₂ has one carbon atom bonded to two oxygen atoms." },
    { q: "Which type of reproduction requires only one parent?", o: ["Sexual", "Asexual", "Binary", "Meiotic"], a: 1, f: "Asexual reproduction produces offspring from a single parent, e.g. budding, cloning." },
    { q: "What is the largest organ in the human body?", o: ["Liver", "Brain", "Skin", "Lung"], a: 2, f: "The skin is the largest organ, protecting the body and regulating temperature." },
    { q: "In which layer of the Earth do tectonic plates move?", o: ["Crust", "Inner core", "Outer core", "Mantle"], a: 3, f: "Tectonic plates float on the semi-fluid upper mantle (asthenosphere)." },
    { q: "What particle has a negative charge?", o: ["Proton", "Neutron", "Electron", "Photon"], a: 2, f: "Electrons carry a negative charge and orbit the nucleus of an atom." },
    { q: "What does DNA stand for?", o: ["Deoxyribonucleic Acid", "Deoxyribose Nitrogen Acid", "Diribonucleic Acid", "Double Nitrogen Acid"], a: 0, f: "DNA (Deoxyribonucleic Acid) carries genetic information in living organisms." },
  ],
  "8": [
    { q: "What is Newton's Second Law of Motion?", o: ["F = mv", "F = ma", "F = m/a", "F = a/m"], a: 1, f: "Newton's 2nd Law: Force = mass × acceleration. More mass or acceleration = more force." },
    { q: "Which acid is found in the stomach?", o: ["Sulfuric acid", "Nitric acid", "Hydrochloric acid", "Citric acid"], a: 2, f: "The stomach produces hydrochloric acid (HCl) to digest food and kill bacteria." },
    { q: "What is the pH of a neutral solution?", o: ["0", "5", "7", "14"], a: 2, f: "pH 7 is neutral. Below 7 is acidic; above 7 is alkaline/basic." },
    { q: "Which gas makes up most of Earth's atmosphere?", o: ["Oxygen", "Carbon Dioxide", "Argon", "Nitrogen"], a: 3, f: "Nitrogen makes up about 78% of the atmosphere; oxygen is only ~21%." },
    { q: "What type of wave is sound?", o: ["Transverse", "Longitudinal", "Electromagnetic", "Surface"], a: 1, f: "Sound travels as a longitudinal wave — compressions and rarefactions in a medium." },
    { q: "What does the law of conservation of energy state?", o: ["Energy can be created", "Energy can be destroyed", "Energy cannot be created or destroyed", "Energy equals mass"], a: 2, f: "Energy is never created or destroyed — it only transforms from one form to another." },
    { q: "What is the chemical symbol for gold?", o: ["Go", "Gd", "Au", "Ag"], a: 2, f: "Gold's symbol Au comes from the Latin word 'Aurum'." },
    { q: "Which type of bond involves sharing of electrons?", o: ["Ionic", "Metallic", "Covalent", "Hydrogen"], a: 2, f: "Covalent bonds form when atoms share electron pairs. E.g. H₂O, CO₂." },
    { q: "What is the SI unit of electric current?", o: ["Volt", "Watt", "Ohm", "Ampere"], a: 3, f: "Electric current is measured in Amperes (A), named after André-Marie Ampère." },
    { q: "Which part of the brain controls balance and coordination?", o: ["Cerebrum", "Cerebellum", "Medulla", "Hypothalamus"], a: 1, f: "The cerebellum coordinates movement, balance, and fine motor skills." },
  ],
  "9": [
    { q: "What is the formula for kinetic energy?", o: ["KE = mv", "KE = ½mv²", "KE = mgh", "KE = mv²"], a: 1, f: "Kinetic Energy = ½ × mass × velocity². Doubling speed quadruples KE." },
    { q: "In an atom, where are electrons found?", o: ["In the nucleus", "Around the nucleus in shells", "In the proton", "Inside neutrons"], a: 1, f: "Electrons occupy energy shells (orbitals) around the nucleus." },
    { q: "What is the process of cell division that produces 4 genetically different cells?", o: ["Mitosis", "Meiosis", "Binary fission", "Budding"], a: 1, f: "Meiosis produces 4 haploid cells for sexual reproduction, each genetically unique." },
    { q: "Which element has atomic number 6?", o: ["Calcium", "Nitrogen", "Carbon", "Oxygen"], a: 2, f: "Carbon (C) has 6 protons, giving it atomic number 6. It's the basis of all life." },
    { q: "What is Ohm's Law?", o: ["V = IR", "I = VR", "R = VI", "V = I/R"], a: 0, f: "Ohm's Law: Voltage (V) = Current (I) × Resistance (R)." },
    { q: "Which type of radiation is stopped by a sheet of paper?", o: ["Beta", "Gamma", "Alpha", "X-ray"], a: 2, f: "Alpha particles are the largest and least penetrating — stopped by paper or skin." },
    { q: "What is the role of ribosomes in a cell?", o: ["Energy production", "Protein synthesis", "DNA replication", "Lipid storage"], a: 1, f: "Ribosomes are the cell's protein factories, translating mRNA into proteins." },
    { q: "What is the acceleration due to gravity on Earth?", o: ["8.9 m/s²", "9.8 m/s²", "10.8 m/s²", "11 m/s²"], a: 1, f: "Earth's gravitational acceleration is approximately 9.8 m/s² (often rounded to 10)." },
    { q: "Which process converts glucose into energy without oxygen?", o: ["Aerobic respiration", "Photosynthesis", "Anaerobic respiration", "Transpiration"], a: 2, f: "Anaerobic respiration produces energy without O₂, creating lactic acid or ethanol." },
    { q: "What is the speed of light in a vacuum?", o: ["3 × 10⁶ m/s", "3 × 10⁸ m/s", "3 × 10¹⁰ m/s", "3 × 10⁴ m/s"], a: 1, f: "Light travels at approximately 3 × 10⁸ m/s (300,000 km/s) in a vacuum." },
  ],
  "10": [
    { q: "What is the half-life of a radioactive substance?", o: ["Time for all atoms to decay", "Time for half the atoms to decay", "Time for one atom to decay", "Time for energy to be released"], a: 1, f: "Half-life is the time it takes for half the radioactive nuclei in a sample to decay." },
    { q: "Which type of isomerism involves compounds with the same molecular formula but different structural arrangements?", o: ["Optical isomerism", "Geometric isomerism", "Structural isomerism", "Chain isomerism"], a: 2, f: "Structural isomers share a molecular formula but differ in how atoms are bonded." },
    { q: "What is Faraday's First Law of Electrolysis?", o: ["Mass deposited is proportional to time", "Mass deposited is proportional to charge passed", "Mass deposited is proportional to voltage", "Mass deposited is proportional to resistance"], a: 1, f: "Faraday's 1st Law: Mass of substance deposited is proportional to the charge passed." },
    { q: "In genetics, what does 'heterozygous' mean?", o: ["Both alleles are identical", "One dominant, one recessive allele", "Both alleles are recessive", "No alleles present"], a: 1, f: "Heterozygous means having two different alleles for a gene (e.g., Aa)." },
    { q: "Which law states that gas pressure and volume are inversely proportional at constant temperature?", o: ["Charles's Law", "Gay-Lussac's Law", "Boyle's Law", "Dalton's Law"], a: 2, f: "Boyle's Law: P₁V₁ = P₂V₂ at constant temperature — pressure and volume are inversely proportional." },
    { q: "What is the function of the nephron?", o: ["Oxygenate blood", "Filter blood and produce urine", "Digest proteins", "Produce hormones"], a: 1, f: "Nephrons are the functional units of the kidney, filtering blood and forming urine." },
    { q: "What type of reaction releases heat to the surroundings?", o: ["Endothermic", "Exothermic", "Photosynthetic", "Electrolytic"], a: 1, f: "Exothermic reactions release energy as heat. Combustion and neutralization are examples." },
    { q: "Which force keeps electrons in orbit around the nucleus?", o: ["Gravitational force", "Magnetic force", "Electrostatic (Coulomb) force", "Nuclear force"], a: 2, f: "The electrostatic attraction between the positive nucleus and negative electrons keeps them bound." },
    { q: "What is the primary function of mRNA?", o: ["Stores genetic information permanently", "Carries genetic code from DNA to ribosomes", "Builds cell walls", "Transports amino acids"], a: 1, f: "mRNA (messenger RNA) carries a copy of the DNA code to the ribosome for protein synthesis." },
    { q: "Which enzyme breaks down hydrogen peroxide in cells?", o: ["Amylase", "Lipase", "Catalase", "Protease"], a: 2, f: "Catalase breaks H₂O₂ into water and oxygen, preventing cellular damage." },
  ],
  "11": [
    { q: "What is the equation for calculating electrical power?", o: ["P = I/V", "P = IV", "P = V/I", "P = I²/V"], a: 1, f: "Electrical Power P = Current × Voltage (P = IV). Also written as P = I²R or V²/R." },
    { q: "In Hardy-Weinberg equilibrium, which condition is NOT required?", o: ["Large population", "No mutation", "Random natural selection", "No gene flow"], a: 2, f: "Hardy-Weinberg requires no natural selection. Random selection would disrupt allele frequencies." },
    { q: "What does the Heisenberg Uncertainty Principle state?", o: ["Energy is quantized", "Position and momentum cannot both be precisely known simultaneously", "Electrons have wave-particle duality", "Force equals mass times acceleration"], a: 1, f: "You cannot simultaneously know the exact position and momentum of a particle — measuring one disturbs the other." },
    { q: "Which type of bond is responsible for the high boiling point of water?", o: ["Ionic bond", "Covalent bond", "Metallic bond", "Hydrogen bond"], a: 3, f: "Hydrogen bonds between water molecules require significant energy to break, giving water a high boiling point." },
    { q: "What is the term for the minimum energy required to start a chemical reaction?", o: ["Enthalpy", "Entropy", "Activation energy", "Bond energy"], a: 2, f: "Activation energy is the minimum energy needed to break bonds and start a reaction." },
    { q: "Which hormone regulates blood glucose levels by promoting its uptake into cells?", o: ["Glucagon", "Adrenaline", "Insulin", "Cortisol"], a: 2, f: "Insulin (from the pancreas) lowers blood glucose by promoting glucose uptake into cells." },
    { q: "What is the formula for calculating pressure?", o: ["P = Force / Area", "P = Force × Area", "P = Area / Force", "P = Force + Area"], a: 0, f: "Pressure = Force ÷ Area. Units are Pascals (Pa) = N/m²." },
    { q: "In organic chemistry, what is the general formula for alkanes?", o: ["CₙH₂ₙ", "CₙHₙ", "CₙH₂ₙ₊₂", "CₙH₂ₙ₋₂"], a: 2, f: "Alkanes have the formula CₙH₂ₙ₊₂. Methane is CH₄, ethane is C₂H₆, etc." },
    { q: "What does ATP stand for in biology?", o: ["Amino Triphosphate", "Adenosine Triphosphate", "Adenine Transfer Protein", "Active Transport Protein"], a: 1, f: "ATP (Adenosine Triphosphate) is the universal energy currency of all living cells." },
    { q: "Which law relates to the conservation of momentum?", o: ["Newton's 1st Law", "Newton's 2nd Law", "Newton's 3rd Law", "Hooke's Law"], a: 2, f: "Newton's 3rd Law (equal and opposite forces) is the basis for conservation of momentum in collisions." },
  ],
};

export function quizForGrade(grade: string): Question[] {
  return QUESTION_BANK[grade] || QUESTION_BANK["6"];
}
